#!/bin/sh

# this is just an example!
# add your autostart stuffs here
xbacklight -set 5 &
xmodmap ~/.xmodmap-sid &

# Start up the compositor
picom &
# Start up the notification daemon
dunst &

xrdb merge ~/.Xresources &

# Load the wallpaper
feh --bg-fill ~/Pictures/wall/pink-cat.png &

# run bar script and dwm ( do not remove this )
~/.config/dwm/scripts/./bar.sh &
dwm
